[package]
name = "ncgmgr"
version = "0.1.0"
description = "A Tauri App"
authors = [ "inkfarer" ]
license = ""
repository = ""
default-run = "ncgmgr"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.4", features = [] }

[dependencies]
serde_json = "1.0.79"
serde = { version = "1.0.136", features = [ "derive" ] }
git2 = "0.14.2"
semver-parser = "0.10.2"
itertools = "0.10.3"
unwrap_or = "1.0.0"

[dependencies.tauri]
version = "1.0.0-rc.4"
features = ["api-all"]

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
