name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets['GITHUB_TOKEN'] }}
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint on source
        run: yarn lint

      - name: Run tests
        run: yarn test:ci

      - name: Create test report
        if: ${{ always() }}
        uses: tanmen/jest-reporter@v1
        with:
          github-token: ${{ secrets['GITHUB_TOKEN'] }}
          result-file: ./result.json

  build-publish:
    if: github.ref == 'refs/heads/master'
    timeout-minutes: 30
    needs: test
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          cache: 'yarn'

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install app dependencies and build it
        run: yarn install && yarn tauri:build

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ncgmgr-v__VERSION__
          releaseName: "NCGMGR v__VERSION__"
          releaseDraft: true
