name: "publish"
on:
  push:
    branches:
      - master

jobs:
  build-publish:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets['GITHUB_TOKEN'] }}
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: ./

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install app dependencies and build it
        run: npm i && npm run build

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ncgmgr-v__VERSION__
          releaseName: "NCGMGR v__VERSION__"
          releaseDraft: true
          prerelease: false
