name: CI

on:
  push:
  pull_request:
    branches: [ master ]
    types: [ opened, closed ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets['GITHUB_TOKEN'] }}
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: ./NCGMGR

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./NCGMGR
        run: yarn

      - name: Run ESLint on source
        working-directory: ./NCGMGR
        run: yarn lint

      - name: Run tests
        working-directory: ./NCGMGR
        run: yarn test:ci

      - name: Create test report
        if: ${{ always() }}
        uses: tanmen/jest-reporter@v1
        with:
          github-token: ${{ secrets['GITHUB_TOKEN'] }}
          result-file: ./NCGMGR/result.json
